version: '2'
services:
 payara:
  build: ../images/payara
  links:
  - mysql:db
  ports:
  - "8080:8080"
  - "4848:4848"
 mysql:
  build: ../images/mysql
  environment:
  - MYSQL_ROOT_PASSWORD=admin
  ports:
  - "3306:3306"
 phpmyadmin:
  build: ../images/phpmyadmin
  environment:
  - MYSQL_ROOT_PASSWORD=admin
  ports:
  - "6060:80"
  links:
  - mysql:db
